// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WFA_MostPopularCities.Models;

#nullable disable

namespace WFA_MostPopularCities.Migrations
{
    [DbContext(typeof(CityContext))]
    partial class CityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WFA_MostPopularCities.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("CityId");

                    b.HasIndex(new[] { "Name" }, "CityName");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            Name = "Adana"
                        },
                        new
                        {
                            CityId = 6,
                            Name = "Ankara"
                        },
                        new
                        {
                            CityId = 61,
                            Name = "Trabzon"
                        });
                });

            modelBuilder.Entity("WFA_MostPopularCities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProductId");

                    b.HasIndex("CityId");

                    b.HasIndex(new[] { "Name" }, "ProductName");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CityId = 6,
                            Name = "Keçi"
                        },
                        new
                        {
                            ProductId = 2,
                            CityId = 1,
                            Name = "Şırdan"
                        },
                        new
                        {
                            ProductId = 3,
                            CityId = 1,
                            Name = "Aykut Bey"
                        },
                        new
                        {
                            ProductId = 4,
                            CityId = 61,
                            Name = "Tereyağ"
                        },
                        new
                        {
                            ProductId = 5,
                            CityId = 61,
                            Name = "Ekmek"
                        });
                });

            modelBuilder.Entity("WFA_MostPopularCities.Models.Product", b =>
                {
                    b.HasOne("WFA_MostPopularCities.Models.City", "City")
                        .WithMany("Products")
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("WFA_MostPopularCities.Models.City", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
