// <auto-generated />
using Category_Product_Crud.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Category_Product_Crud.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20230502131920_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Category_Product_Crud.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Phone"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Computer"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Television"
                        });
                });

            modelBuilder.Entity("Category_Product_Crud.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2,
                            InStock = true,
                            Name = "Hp",
                            Price = 30000m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            InStock = true,
                            Name = "MacBook",
                            Price = 50000m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            InStock = true,
                            Name = "Apple",
                            Price = 20000m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            InStock = true,
                            Name = "Xiaomi",
                            Price = 12000m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 3,
                            InStock = true,
                            Name = "Samsung",
                            Price = 27500m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3,
                            InStock = true,
                            Name = "Vestel",
                            Price = 32700m
                        });
                });

            modelBuilder.Entity("Category_Product_Crud.Models.Product", b =>
                {
                    b.HasOne("Category_Product_Crud.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Category_Product_Crud.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
